name: "Deployment"

on:
  push:
    branches:
      - main

env:
  APP_NAME: MY_WEBAPP_NAME
  PYTHON_VERSION: '3.11.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: fake build
      run: echo "fake build"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: https://www.google.com

    steps:
    - name: fake deploy
      run: echo "fake deploy"
